modLoader = "javafml"
loaderVersion = "[4,)"
license = "Insert License Here"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Rolling Stones"
authors = "Solstice"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
displayURL="https://github.com/Solstace-MC/Rolling-Stones"
logoFile = "assets/rolling_stones/icon.png"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"
