modLoader = "javafml"
loaderVersion = "[4,)"
license = "Insert License Here"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Rolling Stones"
authors = "Solstice"
description = "Equipment progression overhaul mod that replaces stat upgrading enchantments with unique upgrades."
displayURL="https://github.com/Solstace-MC/Rolling-Stones"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"
