on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 21
                  cache: "gradle"
            - name: Make gradlew executable
              run: chmod +x gradlew
            - name: Build project
              run: ./gradlew clean build
            - name: Publish files
              uses: Kir-Antipov/mc-publish@v3.3
              with:
#                  curseforge-id: "${{ vars.CURSEFORGE_ID }}"
#                  curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"
#                  curseforge-version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
                  modrinth-id: "${{ vars.MODRINTH_ID }}"
                  modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
                  modrinth-version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
                  github-tag: "${{ github.event.release.tag_name }}"
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

                  name: "${{ github.event.release.name }}"
                  version: "${{ github.event.release.tag_name }}"
                  version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
                  changelog: "${{ github.event.release.body }}"
