on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Change Version
              run: sed -i 's/mod_version=.*/mod_version=${{ github.event.release.tag_name }}/g' gradle.properties

            - name: Validate Gradle
              uses: gradle/actions/wrapper-validation@v4
            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 21
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Run Datagen
              run: ./gradlew runDatagen
            - name: Delete Duplicates
              run: find src/main/resources -type f | while read -r file; do rm -f -- "src/main/generated/${file#src/main/resources/}"; done
            - name: Build project
              run: ./gradlew build

            - name: Publish Mod
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  name: "${{ github.event.release.name }}"
                  version: "${{ github.event.release.tag_name }}"
                  version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
                  changelog: "${{ github.event.release.body }}"

                  game-versions: |
                    1.21.1
                  dependencies: |
                    fabric-api
                    euclids-elements

                  github-tag: "${{ github.event.release.tag_name }}"
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
                  modrinth-id: "${{ vars.MODRINTH_ID }}"
                  modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
                  modrinth-version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
